### ISSUE TITLE
URGENT How to render ID without year or edition?

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#193]
I'm trying to render ID without year or edition using:
```ruby
id = Pubid::Nist::Identifier.parse 'NIST IR 8200-2018'

id.to_s year: false
NoMethodError: undefined method `+' for nil:NilClass
from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-nist-0.2.1/lib/pubid/nist/renderer.rb:50:in `render_edition'

id.to_s edition: false
NoMethodError: undefined method `+' for nil:NilClass
from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-nist-0.2.1/lib/pubid/nist/renderer.rb:50:in `render_edition'
```
Is this an error or there is another way to render without year/edition?

**Comment by ronaldtse** [comment]
@mico can you please help?
