### ISSUE TITLE
NistTechPubs#fetch broken

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-nist#233]
https://raw.githubusercontent.com/usnistgov/NIST-Tech-Pubs/nist-pages/xml/allrecords.xml is not available anymore so NistTechPubs#fetch returns nothing, tests failing:

```
404 Not Found

expected [] to include "NBS BH 1", "NIST SP 1800-15", "NIST SP 1265", "NBS FIPS 83", and "NIST IR 8379"

  0) Pubid::Nist::NistTechPubs#fetch fetch doc identifiers from nist_tech_pubs
     Failure/Error:
       expect(described_class.fetch.map { |d| d[:id] })
         .to include("NBS BH 1",
                     "NIST SP 1800-15",
                     "NIST SP 1265",
                     "NBS FIPS 83",
                     "NIST IR 8379")

       expected [] to include "NBS BH 1", "NIST SP 1800-15", "NIST SP 1265", "NBS FIPS 83", and "NIST IR 8379"
     # ./spec/nist_pubid/nist_tech_pubs_spec.rb:4:in `block (3 levels) in <top (required)>'
     # /Users/mico/.rvm/gems/ruby-3.2.2/gems/webmock-3.19.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
1 example, 1 failure, 0 passed
Finished in 0.140681 seconds
```

**Comment by ronaldtse** [comment]
You have to use the new Relaton fetcher.
